[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
btc_margin_vault = "6UVY7nskmCBaeKS22E6oh5CkS9TcdcmazHzLAme4YNfB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
